<ul class="list-disc text-left">
	<li><a href="https://360environmental.com.au/careers/">360Environmental</a></li>
	<li><a href="https://www.2excelaviation.com/careers/">2Excel Geospatial</a></li>
	<li><a href="https://www.3deo.com/careers">3DEO</a></li>
	<li><a href="https://www.4earthintelligence.com/about-us/careers/vacancies/">4 Earth Intelligence</a></li>
	<li><a href="https://aamgroup.com/careers/">AAM Group</a></li>
	<li><a href="https://www.acri-st.fr/en/careers">ACRI-ST</a></li>
	<li><a href="https://www.advanced-infrastructure.co.uk/career">Advanced Infrastructure</a></li>
	<li><a href="https://aerialservicesinc.com/careers/">Aerial Services Inc.</a></li>
	<li><a href="https://www.aerialsurveys.co.nz/careers">Aerial Survey Limited</a></li>
	<li><a href="https://aerometrex.com.au/about/careers-aerometrex/">Aerometrex</a></li>
	<li><a href="https://www.aerospacelab.be/join-our-team/">Aerospacelab</a></li>
	<li><a href="https://www.aeroterra.com/es-ar/trabaja-con-nosotros/busquedas-actuales">Aeroterra</a></li>
	<li><a href="https://www.aresys.it/careers/#open-positions">Aersys</a></li>
	<li><a href="https://www.agerpoint.com/careers">Agerpoint</a></li>
	<li><a href="https://www.telus.com/agcg/careers/positions">Agrian</a></li>
	<li><a href="https://jobs.lever.co/aidash">AI Clearing</a></li>
	<li><a href="https://www.airbornetechnologies.at/en/jobs/">Airborne Technologies</a></li>
	<li><a href="https://aistechspace.com/careers/">Aistech</a></li>
	<li><a href="https://www.albaorbital.com/careers">Alba Orbital</a></li>
	<li><a href="https://jobs.lever.co/albedo">Albedo</a></li>
	<li><a href="https://www.alcis.org/opportunities">Alcis</a></li>
	<li><a href="https://allsourceanalysis.com/careers/">Allsource Analysis</a></li>
	<li><a href="https://alteia.com/company/careers/">Alteia</a></li>
	<li><a href="https://www.anditi.com/careers">Anditi</a></li>
	<li><a href="https://angelswing.notion.site/Korean-Drone-Data-Startup-Angelswing-is-Recruiting-Software-Engineers-in-Nepal-03a3774841bf4ac4a5b8e2bac21b0e3f">Angelswing</a></li>
	<li><a href="https://www.appgeo.com/careers/">AppGeo</a></li>
	<li><a href="https://www.linkedin.com/company/arable-labs-inc./jobs/">Arable</a></li>
	<li><a href="https://www.arbonaut.com/en/about-us/careers">Arbonaut</a></li>
	<li><a href="https://argans.co.uk/careers.html">Argans</a></li>
	<li><a href="https://www.ariespace.com/lavora-con-noi/">Ariespace</a></li>
	<li><a href="https://www.arlula.com/careers/">Arlula</a></li>
	<li><a href="https://jobs.lever.co/Arturo">Arturo</a></li>
	<li><a href="https://www.assimila.earth/about/#careers">Assimila</a></li>
	<li><a href="https://www.astraea.earth/careers">Astraea</a></li>
	<li><a href="http://www.astron.com.au/careers/">Astron</a></li>
	<li><a href="https://astrosat.net/career/">Astrosat</a></li>
	<li><a href="https://atlasai.applytojob.com/apply/">Atlas AI</a></li>
	<li><a href="https://attentive.ai/careers/">Attentive AI</a></li>
	<li><a href="https://aureaimaging.com/#ourMission">Aurea Imaging</a></li>
	<li><a href="https://jobs.lever.co/aurorainsight">Aurora Insight</a></li>
	<li><a href="https://axelspace.applytojob.com/apply">Axelspace</a></li>
	<li><a href="https://careers-aximgeo.icims.com/jobs/intro?hashed=-625947405&mobile=false&width=1693&height=500&bga=true&needsRedirect=false&jan1offset=-300&jun1offset=-240">Axim Geospatial</a></li>
	<li><a href="https://www.ayresassociates.com/careers/">Ayres Associates</a></li>
	<li><a href="https://careers.azavea.com/#openings">Azavea</a></li>
	<li><a href="https://beca.csod.com/ux/ats/careersite/1/home?c=beca">Beca</a></li>
	<li><a href="https://apply.workable.com/betterview/#jobs">Betterview </a></li>
	<li><a href="https://www.biosis.com.au/jobs/">Biosys</a></li>
	<li><a href="https://careers-zonda.icims.com/jobs/search?mobile=false&width=1728&height=500&bga=true&needsRedirect=false&jan1offset=-300&jun1offset=-240">Bird.i</a></li>
	<li><a href="https://www.blacksky.com/careers/">BlackSky</a></li>
	<li><a href="https://www.bluemarblegeo.com/about/careers/">Blue Marble Geographics</a></li>
	<li><a href="https://blueraster.jobs/apply">Blue Raster</a></li>
	<li><a href="https://blueskyhq.io/careers">Blue Sky Analytics</a></li>
	<li><a href="https://www.brockmann-consult.de/career/">Brockmann Consult</a></li>
	<li><a href="https://c-core.ca/careers/">C-Core</a></li>
	<li><a href="https://cadasta.org/about-us-3/careers-2/">Cadasta Foundations</a></li>
	<li><a href="https://www.cadcorp.com/about-us/careers/current-vacancies/">Cadcorp</a></li>
	<li><a href="https://www.caliper.com/jobs.htm">Caliper</a></li>
	<li><a href="https://www.camptocamp.com/career#openpositions">Camptocamp</a></li>
	<li><a href="https://jobs.lever.co/capeanalytics">Cape Analytics</a></li>
	<li><a href="https://www.capellaspace.com/about-us/careers/">Capella Space</a></li>
	<li><a href="https://apply.workable.com/carbonplan/">Carbon Plan</a></li>
	<li><a href="https://jobs.gusto.com/boards/carbon-mapper-inc-3ff9ef6d-ec4f-45af-94e4-2a67e7b31154">Carbon Mapper</a></li>
	<li><a href="https://carto.com/careers/#open-positions">Carto</a></li>
	<li><a href="https://cartovista.com/careers/">Cartovista</a></li>
	<li><a href="https://catalyst.earth/about/careers/">Catalyst</a></li>
	<li><a href="https://app.beapplied.com/org/1613/satellite-applications-catapult#jobList">Catapult Satellite Applications</a></li>
	<li><a href="https://www.ceresimaging.net/careers?hsCtaTracking=39aafc21-f982-44ca-9914-c3815564be34%7Cfc43d777-822b-4534-9a34-902524c3123c">Ceres Imaging</a></li>
	<li><a href="https://careers.smartrecruiters.com/CGG3/">CGG</a></li>
	<li><a href="https://www.paycomonline.net/v4/ats/web.php/jobs?clientkey=14B329E3D0A2E479F3FE06280008FB70">Chesapeake Conservancy</a></li>
	<li><a href="https://chloris.bamboohr.com/careers">Chloris Geospatial</a></li>
	<li><a href="https://climate.eightfold.ai/careers">Climate Cooperation</a></li>
	<li><a href="https://climateengine.com/careers/">Climate Engine</a></li>
	<li><a href="https://www.climate-x.com/careers">Climate X</a></li>
	<li><a href="https://boards.greenhouse.io/climavision/">Climavision</a></li>
	<li><a href="https://boards.greenhouse.io/cloudtostreet/">Cloud to Street</a></li>
	<li><a href="https://www.cloudeo.group/join-us">cloudEO</a></li>
	<li><a href="https://codex.com.br/sobre/#trabalheconosco">codex</a></li>
	<li><a href="https://www.cls.fr/nous-rejoindre/nos-offres-d-emploi/">Collecte Localisation Satellites (CLS)</a></li>
	<li><a href="https://constellr.recruitee.com/">ConstellR</a></li>
	<li><a href="https://www.con-terra.com/jobs-and-internships">con terra</a></li>
</ul>